services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/db?sslmode=disable  # Используйте имя сервиса
    depends_on:
      db:
        condition: service_healthy  # Условие для проверки состояния

  db:
    image: bitnami/postgresql:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
